"""Word list: the built-in healthcare + everyday vocabulary
(app/data/sign_metadata.csv, generated by ml/generate_sign_metadata.py) plus
custom words added from the app (DATA_DIR/custom_signs.csv).

Each word carries the English and Tamil text shown and spoken once its sign
is recognized. The Tamil is a written-language translation, not a
description of the sign itself.
"""

import csv
import os
import re
import threading
from typing import Dict, List, Optional

from app import config

FIELDS = ["sign_id", "concept", "english", "tamil", "category", "is_emergency", "source"]
CUSTOM_CATEGORY = "CUSTOM"

_BUILTIN_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "sign_metadata.csv")


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.strip().lower()).strip("_")


def _read(path: str) -> List[dict]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _write(path: str, rows: List[dict]):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    os.replace(path + ".tmp", path)


class Vocabulary:
    def __init__(self, builtin_path: str = _BUILTIN_PATH):
        self._builtin_path = builtin_path
        self._lock = threading.Lock()
        self.by_id: Dict[str, dict] = {}
        self.by_concept: Dict[str, dict] = {}
        self.reload()

    def reload(self):
        by_id, by_concept = {}, {}
        for row in _read(self._builtin_path) + _read(config.custom_signs_path()):
            by_id[row["sign_id"]] = row
            by_concept[row["concept"]] = row
        self.by_id, self.by_concept = by_id, by_concept

    def get(self, sign_id: str) -> Optional[dict]:
        return self.by_id.get(sign_id)

    def get_by_concept(self, concept: str) -> Optional[dict]:
        return self.by_concept.get(concept)

    def list_all(self, category: Optional[str] = None) -> List[dict]:
        rows = list(self.by_id.values())
        if category:
            rows = [r for r in rows if r["category"] == category]
        return rows

    def categories(self) -> List[str]:
        return list(dict.fromkeys(r["category"] for r in self.by_id.values()))

    def is_emergency(self, concept: str) -> bool:
        row = self.by_concept.get(concept)
        return bool(row and row["is_emergency"] == "yes")

    def add_custom(self, english: str, tamil: str, category: str = CUSTOM_CATEGORY,
                   is_emergency: bool = False) -> dict:
        concept = slugify(english)
        if not concept:
            raise ValueError("The English text must contain letters or numbers.")
        with self._lock:
            if concept in self.by_concept:
                raise ValueError(f"'{english.strip()}' is already in the vocabulary.")
            path = config.custom_signs_path()
            custom = _read(path)
            numbers = [int(r["sign_id"][2:]) for r in custom if r["sign_id"][2:].isdigit()]
            row = {
                "sign_id": f"CU{max(numbers, default=0) + 1:03d}",
                "concept": concept,
                "english": english.strip(),
                "tamil": tamil.strip(),
                "category": slugify(category).upper() or CUSTOM_CATEGORY,
                "is_emergency": "yes" if is_emergency else "no",
                "source": "custom",
            }
            _write(path, custom + [row])
            self.reload()
        return row

    def delete_custom(self, sign_id: str) -> dict:
        with self._lock:
            row = self.by_id.get(sign_id)
            if row is None:
                raise KeyError(sign_id)
            if row["source"] != "custom":
                raise ValueError("Built-in words can't be deleted.")
            path = config.custom_signs_path()
            _write(path, [r for r in _read(path) if r["sign_id"] != sign_id])
            self.reload()
        return row


vocabulary = Vocabulary()
