"""Word list, stored in the `words` table.

The built-in healthcare + everyday words (app/data/sign_metadata.csv,
generated by ml/generate_sign_metadata.py) are added the first time the
database is set up. Trainers propose new words, which stay pending until an
admin approves them. Only approved words are shown to the public, recognized
and trained.

Each word carries the English and Tamil text shown and spoken once its sign
is recognized. The Tamil is a written-language translation, not a
description of the sign itself.

Recognition looks words up several times a second, so approved words are
cached in memory: reloaded after every change made through this process,
and every CACHE_SECONDS in case another process changed them.
"""

import csv
import os
import re
import time
from typing import Dict, List, Optional

from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app import db as database
from app.errors import ApiError
from app.models.tables import APPROVED, PENDING, User, Word, utcnow

CUSTOM_CATEGORY = "CUSTOM"
CACHE_SECONDS = 30
_ADD_WORD_LOCK = 72_201  # advisory lock id: words are added one at a time, so sign ids never collide

_BUILTIN_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "sign_metadata.csv")


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.strip().lower()).strip("_")


def word_dict(word: Word) -> dict:
    return {
        "sign_id": word.sign_id,
        "concept": word.concept,
        "english": word.english,
        "tamil": word.tamil,
        "category": word.category,
        "is_emergency": word.is_emergency,
        "source": word.source,
        "status": word.status,
    }


class Vocabulary:
    """The approved words, cached."""

    def __init__(self):
        self._by_id: Dict[str, dict] = {}
        self._by_concept: Dict[str, dict] = {}
        self._loaded_at: Optional[float] = None

    def reload(self):
        with database.session_scope() as db:
            rows = [word_dict(w) for w in db.scalars(select(Word).where(Word.status == APPROVED).order_by(Word.id))]
        self._by_id = {row["sign_id"]: row for row in rows}
        self._by_concept = {row["concept"]: row for row in rows}
        self._loaded_at = time.monotonic()

    def _fresh(self) -> "Vocabulary":
        if self._loaded_at is None or time.monotonic() - self._loaded_at > CACHE_SECONDS:
            self.reload()
        return self

    def get(self, sign_id: str) -> Optional[dict]:
        return self._fresh()._by_id.get(sign_id)

    def get_by_concept(self, concept: str) -> Optional[dict]:
        return self._fresh()._by_concept.get(concept)

    def list_all(self, category: Optional[str] = None) -> List[dict]:
        rows = list(self._fresh()._by_id.values())
        if category:
            rows = [r for r in rows if r["category"] == category]
        return rows

    def categories(self) -> List[str]:
        return list(dict.fromkeys(r["category"] for r in self._fresh()._by_id.values()))

    def is_emergency(self, concept: str) -> bool:
        row = self.get_by_concept(concept)
        return bool(row and row["is_emergency"])


vocabulary = Vocabulary()


def seed_builtin_words(db: Session) -> int:
    """Adds built-in words that aren't in the table yet. Existing rows, including an admin's edits, are kept."""
    sign_ids = set(db.scalars(select(Word.sign_id)))
    concepts = set(db.scalars(select(Word.concept)))
    added = 0
    with open(_BUILTIN_PATH, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            if row["sign_id"] in sign_ids or row["concept"] in concepts:
                continue
            db.add(Word(
                sign_id=row["sign_id"], concept=row["concept"], english=row["english"], tamil=row["tamil"],
                category=row["category"], is_emergency=row["is_emergency"] == "yes", source="builtin", status=APPROVED,
            ))
            added += 1
    db.flush()
    return added


def _next_sign_id(db: Session) -> str:
    numbers = [int(s[2:]) for s in db.scalars(select(Word.sign_id).where(Word.sign_id.like("CU%"))) if s[2:].isdigit()]
    return f"CU{max(numbers, default=0) + 1:03d}"


def add_word(db: Session, english: str, tamil: str, category: str = CUSTOM_CATEGORY, is_emergency: bool = False, *,
             status: str = APPROVED, proposed_by: Optional[User] = None) -> Word:
    """Adds a word (approved, or pending review). A previously rejected word can be proposed again."""
    concept = slugify(english)
    if not concept:
        raise ApiError(422, "invalid_word", "The English text must contain letters or numbers.")
    db.execute(text("SELECT pg_advisory_xact_lock(:key)"), {"key": _ADD_WORD_LOCK})
    word = db.scalar(select(Word).where(Word.concept == concept))
    if word is not None and word.status == APPROVED:
        raise ApiError(409, "word_exists", f"'{english.strip()}' is already in the vocabulary.")
    if word is not None and word.status == PENDING:
        raise ApiError(409, "word_pending", f"'{english.strip()}' was already proposed and is waiting for review.")
    if word is None:
        word = Word(sign_id=_next_sign_id(db), concept=concept, source="custom")
        db.add(word)
    word.english = english.strip()
    word.tamil = tamil.strip()
    word.category = slugify(category).upper() or CUSTOM_CATEGORY
    word.is_emergency = is_emergency
    word.status = status
    word.proposed_by_id = proposed_by.id if proposed_by else None
    word.reviewed_by_id, word.reviewed_at, word.review_note = None, None, None
    word.created_at = utcnow()
    db.flush()
    return word
